name: MiniAnnouncerLegacy
version: '${project.version}'
main: me.jonakls.miniannouncerlegacy.MiniAnnouncerLegacy
authors: [ Jonakls ]
description: Simple automatic announcer with MiniMessage!
softdepend:
  - PlaceholderAPI
commands:
  miniannouncer:
    description: General command of plugin
    aliases:
      - ma
      - minia
      - announcer
